name: wfcon

on: 
  push:
    paths:
      - '.github/workflows/jobcon.yaml'

jobs:
  jj:
    runs-on: ubuntu-latest
    concurrency:
      group: my-group
      cancel-in-progress: true
    steps:
      - run: sleep 10m

# 1
